### PR TITLE
Block adult category

### PR DESCRIPTION
**Pull request by elros34**

### CODE REVIEW

**Comment by nobodyinperson** [comment]
Very good idea! 

However, I think the user should probably have the possibility to unhide the category. Otherwise there'll most likely be complaints...

**Comment by mentaljam** [comment]
Sorry for a long reply. I'll try to look at your PR this weekend.

**Comment by Olf0** [comment]
Well, a lot of effort and code to maintain just to create ones own filter bubble.
Such stuff exists and nothing is forcing one to look at or even install "adult" packages.

But if you @osetr really consider to merge this, it should be opt-in and easily reversible at the GUI, in order not to discriminate such packages and their authors.

**Comment by nobodyinperson** [comment]
Completely agree with @Olf0. The changes introduced by this PR are not enough in this regard. Basically #107 would be the way to go.

**Comment by Olf0** [comment]
ACK, implementing #107 would provide a nice, generic and non-discriminatory way to handle this.

**Comment by elros34** [comment]
Such a content is plain wrong and should not be promoted in any way even if it's easily available elsewhere. I hope @mentaljam do not want to spread it through his application.

**Comment by mentaljam** [comment]
@elros34 I really don't think that force blocking of any categories is a good idea. I have implemented an option to hide categories by selection which gives a user the ability to make their own decision.

**Pull request closed without merging**
